Script started on 2020-02-13 16:20:09-0500
]0;aj@aj-VirtualBox: ~/Documents/cs214/Labs/Lab02[01;32maj@aj-VirtualBox[00m:[01;34m~/Documents/cs214/Labs/Lab02[00m$ cat h[Kexample6.lex
%{
#include <stdio.h>
#include <stdlib.h>   /* atoi()*/
#include <string.h>   /*strcmp()*/
#include "example6.tab.h"
%}
%%
[0-9]+                  yylval = atoi(yytext); return NUMBER;
heat                    return TOKHEAT;
on|off                  yylval = !strcmp(yytext, "on"); return STATE;
set                     return TOKSET;
temperature             return TOKTEMPERATURE;
humidity		return TOKHUMIDITY;
\n                      /* ignore end of line */;
[ \t]+                  /* ignore whitespace */;
%%                
]0;aj@aj-VirtualBox: ~/Documents/cs214/Labs/Lab02[01;32maj@aj-VirtualBox[00m:[01;34m~/Documents/cs214/Labs/Lab02[00m$ cat example6.y
%{
#include <stdio.h>
#include <string.h>

/* declarations */
int yylex (void);
void yyerror (char const *);
int yyparse(void);

/* definitions */
void yyerror(const char *str) {
        fprintf(stderr,"error: %s\n",str);
}

int yywrap() {
        return 1;
}

int main() {
        yyparse();
}

%}

%token NUMBER TOKHEAT STATE TOKSET TOKTEMPERATURE TOKHUMIDITY
%%


commands: /* empty */
        | commands command
        ;

command:
        heat_switch
        | temperature_set
	| humidity_set
        ;

heat_switch:
        TOKHEAT STATE
        {
                if ($2) {  /* if STATE == 1 */
                        printf("\tHeat turned on\n");
                } else {
                        printf("\tHeat turned off\n");
                }
        }
        ;

temperature_set:
        TOKSET TOKTEMPERATURE NUMBER
        {
                printf("\tTemperature set to %d\n",$3);
        }
        ;
humidity_set:
	TOKSET TOKHUMIDITY NUMBER
	{
		printf("\tHumidity set to %d\n", $3);
	}
	;
]0;aj@aj-VirtualBox: ~/Documents/cs214/Labs/Lab02[01;32maj@aj-VirtualBox[00m:[01;34m~/Documents/cs214/Labs/Lab02[00m$ glex [K[K[K[K[Kflex example6.lex
]0;aj@aj-VirtualBox: ~/Documents/cs214/Labs/Lab02[01;32maj@aj-VirtualBox[00m:[01;34m~/Documents/cs214/Labs/Lab02[00m$ bison-[K -b[Kd example6.y
]0;aj@aj-VirtualBox: ~/Documents/cs214/Labs/Lab02[01;32maj@aj-VirtualBox[00m:[01;34m~/Documents/cs214/Labs/Lab02[00m$ gcc lex.yy.c example6..[Ktab.c -0 [K[Ko example6
]0;aj@aj-VirtualBox: ~/Documents/cs214/Labs/Lab02[01;32maj@aj-VirtualBox[00m:[01;34m~/Documents/cs214/Labs/Lab02[00m$ ./example6
heat on
	Heat turned on
heat off
	Heat turned off
set temperature 56
	Temperature set to 56
set humidity 10
	Humidity set to 10
]0;aj@aj-VirtualBox: ~/Documents/cs214/Labs/Lab02[01;32maj@aj-VirtualBox[00m:[01;34m~/Documents/cs214/Labs/Lab02[00m$ exit

Script done on 2020-02-13 16:22:03-0500
